modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="candycraft"
version="0.1"
displayName="CandyCraft"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="candycraft.png"
#credits=""
authors="Cryptic Mushroom"
description='''

'''
[[dependencies.candycraft]]
    modId="forge"
    mandatory=true
    versionRange="[28,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.candycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"