package com.crypticmushroom.candycraft.world.biomes;

import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerCandyIsland extends GenLayer {
    public GenLayerCandyIsland(long par1) {
        super(par1);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall amounts, or biomeList[] indices
     * based on the particular GenLayer subclass.
     */
    @Override
    public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight) {
        int[] aint = IntCache.getIntCache(areaWidth * areaHeight);

        for (int i1 = 0; i1 < areaHeight; ++i1) {
            for (int j1 = 0; j1 < areaWidth; ++j1) {
                initChunkSeed(areaX + j1, areaY + i1);
                aint[j1 + i1 * areaWidth] = nextInt(10) == 0 ? Biome.getIdForBiome(CCBiomes.candyPlains) : Biome.getIdForBiome(CCBiomes.candyOcean);
            }
        }

        if (areaX > -areaWidth && areaX <= 0 && areaY > -areaHeight && areaY <= 0) {
            aint[-areaX + -areaY * areaWidth] = Biome.getIdForBiome(CCBiomes.candyPlains);
        }

        return aint;
    }
}
