package com.crypticmushroom.candycraft.world.biomes;

import net.minecraft.init.Biomes;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerCandyRiverMix extends GenLayer {
    private GenLayer biomePatternGeneratorChain;
    private GenLayer riverPatternGeneratorChain;

    public GenLayerCandyRiverMix(long p_i2129_1_, GenLayer genLayer, GenLayer genLayer1) {
        super(p_i2129_1_);
        biomePatternGeneratorChain = genLayer;
        riverPatternGeneratorChain = genLayer1;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the
     * world's global seed (passed in as an argument).
     */
    @Override
    public void initWorldGenSeed(long seed) {
        biomePatternGeneratorChain.initWorldGenSeed(seed);
        riverPatternGeneratorChain.initWorldGenSeed(seed);
        super.initWorldGenSeed(seed);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall amounts, or biomeList[] indices
     * based on the particular GenLayer subclass.
     */
    @Override
    public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight) {
        int[] aint = biomePatternGeneratorChain.getInts(areaX, areaY, areaWidth, areaHeight);
        int[] aint1 = riverPatternGeneratorChain.getInts(areaX, areaY, areaWidth, areaHeight);
        int[] aint2 = IntCache.getIntCache(areaWidth * areaHeight);

        for (int i1 = 0; i1 < areaWidth * areaHeight; ++i1) {
            if (aint[i1] != Biome.getIdForBiome(CCBiomes.candyOcean) && aint[i1] != Biome.getIdForBiome(CCBiomes.candyHellForest)) {
                if (aint1[i1] == Biome.getIdForBiome(CCBiomes.candyRiver)) {
                    if (aint[i1] == Biome.getIdForBiome(Biomes.ICE_PLAINS)) {
                        aint2[i1] = Biome.getIdForBiome(Biomes.FROZEN_RIVER);
                    } else if (aint[i1] != Biome.getIdForBiome(Biomes.MUSHROOM_ISLAND) && aint[i1] != Biome.getIdForBiome(Biomes.MUSHROOM_ISLAND_SHORE)) {
                        aint2[i1] = aint1[i1] & 255;
                    } else {
                        aint2[i1] = Biome.getIdForBiome(Biomes.MUSHROOM_ISLAND_SHORE);
                    }
                } else {
                    aint2[i1] = aint[i1];
                }
            } else {
                aint2[i1] = aint[i1];
            }
        }

        return aint2;
    }
}
